config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'

  resources :articles do
    put :head_sort
    put :text_sort
    put :relation_sort
    resources :relations
    resources :heads
    resources :texts
  end

end

app/models/head.rb
class Head < ApplicationRecord
  belongs_to :article
  has_one :position, dependent: :destroy
end

app/controllers/heads_controller.rb
class HeadsController < ApplicationController
  before_action :set_head, only: [:show, :edit, :update, :destroy]
  # CSRF保護を無効
  protect_from_forgery except:[:destroy]

  def index
    @heads = Head.all
  end

  def show
  end

  def new
    @head = Head.new
  end

  def edit
  end

  def create
    # binding.pry
    @head = Head.new(head_params)
    @article = Article.find(params[:article_id])
    if @head.save
      # head作成時にそのidに紐付いたpositionも作成する
      @position = Position.new(head_id:@head.id, article_id:@article.id)
      # binding.pry
      @position.save
      render 'head.js.erb'
    else
      redirect_to article_path(params[:article_id])
    end
  end

  def update
    respond_to do |format|
      if @head.update(head_params)
        format.html { redirect_to @head, notice: 'Head was successfully updated.' }
        format.json { render :show, status: :ok, location: @head }
      else
        format.html { render :edit }
        format.json { render json: @head.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    render "head-delete.js.erb"
    @head.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_head
      @head = Head.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def head_params
      params.permit(:head).merge(article_id:params[:article_id])
    end
end

app/helpers/heads_helper.rb
module HeadsHelper
end

app/views/heads/_form.html.haml
= form_for @head do |f|
  - if @head.errors.any?
    #error_explanation
      %h2= "#{pluralize(@head.errors.count, "error")} prohibited this head from being saved:"
      %ul
        - @head.errors.full_messages.each do |message|
          %li= message

  .actions
    = f.submit 'Save'

app/views/heads/_head.html.haml
-# -binding.pry
%div{class:"content-box", id:"#{head.position.id}",index:"#{head.position.position}", data:{model_name: head.class.name.underscore, update_url:article_head_sort_path(@article) }}
  .head-box
    = head.head
    .operation-box.btn{id:"#{head.id}"}
      -# %li 上へ
      -# %li 下へ
      %li#head-delete{action:"/articles/#{@article.id}/heads/#{head.id}"} 削除

app/views/heads/edit.html.haml
%h1 Editing head

= render 'form'

= link_to 'Show', @head
\|
= link_to 'Back', heads_path

app/views/heads/head-delete.js.erb
<%# alert("見出しを削除しました"); %>

app/views/heads/head.js.erb
$(".article-edit-detail-container").append("<%= j(render partial:'heads/head', locals: { head: @head, article: @article }) %>");
$('#head-form').val('');

app/views/heads/index.html.haml
%h1 Listing heads

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @heads.each do |head|
      %tr
        %td= link_to 'Show', head
        %td= link_to 'Edit', edit_head_path(head)
        %td= link_to 'Destroy', head, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Head', new_head_path

app/views/heads/new.html.haml
%h1 New head

= render 'form'

= link_to 'Back', heads_path

app/views/heads/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_head_path(@head)
\|
= link_to 'Back', heads_path