config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'

  resources :articles do
    put :head_sort
    put :text_sort
    put :relation_sort
    resources :relations
    resources :heads
    resources :texts
  end

end

app/models/relation.rb
class Relation < ApplicationRecord
  belongs_to :article
  has_one :position, dependent: :destroy
end

app/controllers/relations_controller.rb
class RelationsController < ApplicationController
  before_action :set_relation, only: [:show, :edit, :update, :destroy]
  protect_from_forgery except:[:destroy]

  # GET /relations
  # GET /relations.json
  def index
    @relations = Relation.all
  end

  # GET /relations/1
  # GET /relations/1.json
  def show
  end

  # GET /relations/new
  def new
    @relation = Relation.new
  end

  # GET /relations/1/edit
  def edit
  end

  # POST /relations
  # POST /relations.json
  def create
    @relation = Relation.new(relation_params)
    @article = Article.find(params[:article_id])
    if @relation.save
      # relation作成時にそのidに紐付いたpositionも作成する
      @position = Position.new(relation_id:@relation.id, article_id:@article.id)
      @position.save
      render 'relation.js.erb'
    else
      redirect_to article_path(params[:article_id])
    end
  end

  # PATCH/PUT /relations/1
  # PATCH/PUT /relations/1.json
  def update
    respond_to do |format|
      if @relation.update(relation_params)
        format.html { redirect_to @relation, notice: 'Relation was successfully updated.' }
        format.json { render :show, status: :ok, location: @relation }
      else
        format.html { render :edit }
        format.json { render json: @relation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /relations/1
  # DELETE /relations/1.json
  def destroy
    if @relation.destroy
      render "relation-delete.js.erb"
    else
      redirect_to article_path(params[:article_id])
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_relation
      @relation = Relation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def relation_params
      params.permit(:relation).merge(article_id:params[:article_id])
    end
end

app/helpers/relations_helper.rb
module RelationsHelper
end

app/views/relations/_form.html.haml
= form_for @relation do |f|
  - if @relation.errors.any?
    #error_explanation
      %h2= "#{pluralize(@relation.errors.count, "error")} prohibited this relation from being saved:"
      %ul
        - @relation.errors.full_messages.each do |message|
          %li= message

  .actions
    = f.submit 'Save'

app/views/relations/_relation.html.haml
%div{class:"content-box", id:"#{relation.position.id}",index:"#{relation.position.position}", data:{model_name: relation.class.name.underscore, update_url:article_relation_sort_path(@article) }}
  =link_to edit_article_path(relation.relation) do
    .relation-box
      %h3
        = Article.find(relation.relation).title
      %p
        = Article.find(relation.relation).explanation
      .operation-box.btn{id:"#{relation.id}"}
        -# %li 上へ
        -# %li 下へ
        %li#relation-delete{action:"/articles/#{@article.id}/relations/#{relation.id}"} 削除

app/views/relations/edit.html.haml
%h1 Editing relation

= render 'form'

= link_to 'Show', @relation
\|
= link_to 'Back', relations_path

app/views/relations/index.html.haml
%h1 Listing relations

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @relations.each do |relation|
      %tr
        %td= link_to 'Show', relation
        %td= link_to 'Edit', edit_relation_path(relation)
        %td= link_to 'Destroy', relation, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Relation', new_relation_path

app/views/relations/new.html.haml
%h1 New relation

= render 'form'

= link_to 'Back', relations_path

app/views/relations/relation-delete.js.erb
<%# alert("関連記事を削除しました") %>

app/views/relations/relation.js.erb
$(".article-edit-detail-container").append("<%= j(render partial:'relations/relation', locals: { relation: @relation }) %>");

app/views/relations/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_relation_path(@relation)
\|
= link_to 'Back', relations_path