config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'

  resources :articles do
    put :head_sort
    put :text_sort
    put :relation_sort
    resources :relations
    resources :heads
    resources :texts
  end

end

app/models/article.rb
class Article < ApplicationRecord
  # include RankedModel

  has_many :heads, dependent: :destroy
  has_many :texts, dependent: :destroy
  has_many :relations, dependent: :destroy
  has_many  :positions, dependent: :destroy

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  # CSRF保護を無効
  protect_from_forgery except:[:update]
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
    # binding.pry
    @heads = @article.heads
    @texts = @article.texts
    @relations = @article.relations
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json
      else
        format.html { render :new }
        format.json
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    # binding.pry
    @article.update(article_params)
    render body: nil
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def head_sort
    # binding.pry
    position = Position.find(params.require(:head)[:id])
    position.update(position: head_position_params[:position_position])
    render body: nil
  end

  def text_sort
    # binding.pry
    position = Position.find(params.require(:text)[:id])
    position.update(position: text_position_params[:position_position])
    render body: nil
  end

  def relation_sort
    # binding.pry
    position = Position.find(params.require(:relation)[:id])
    position.update(position: relation_position_params[:position_position])
    render body: nil
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.permit(:title,:explanation)
    end

    def head_position_params
      params.require(:head).permit(:position_position)
    end

    def text_position_params
      params.require(:text).permit(:position_position)
    end

    def relation_position_params
      params.require(:relation).permit(:position_position)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.haml
.article-container
  =link_to edit_article_path(article) do
    .article-box
      .article-box-title
        %span 【
        %p
          = article.id
        %span 】
        %p
          = article.title
      .article-box-explanation
        %p
          = article.explanation

app/views/articles/_form.html.haml
= form_with(model: article, local: true) do |form|
  - if article.errors.any?
    #error_explanation
      %h2
        = pluralize(article.errors.count, "error")
        prohibited this article from being saved:
      %ul
        - article.errors.full_messages.each do |message|
          %li= message
  .actions
    = form.submit

app/views/articles/edit.html.haml
-# -binding.pry
.articles-top
  .articles-head
    %h1 記事編集（記事ID：
    %h1
      = @article.id
      %span )

  .article-edit
    .article-edit-box
      = form_with model:@article, method: :patch, class:'article-edit-box-form' do |f|
        %h3 ■タイトル
        .article-edit-box-title
          = f.text_area :title, value: @article.title, id:"title-form"
        %h3 ■説明文
        .article-edit-box-explanation
          = f.text_area :explanation, value: @article.explanation, id:"explanation-form"

    .article-edit-detail
      %h3 ■記事内容
      .article-edit-detail-container
        -# 見出し一覧
        -@heads.each do |head|
          %div{class:"content-box", id:"#{head.position.id}",index:"#{head.position.position}", data:{model_name: head.class.name.underscore, update_url:article_head_sort_path(@article) }}
            .head-box
              = head.head
              .operation-box.btn{id:"#{head.id}"}
                -# %li 上へ
                -# %li 下へ
                %li#head-delete{action:"/articles/#{@article.id}/heads/#{head.id}"} 削除

        -# 本文一覧
        -@texts.each do |text|
          %div{class:"content-box",id:"#{text.position.id}",index:"#{text.position.position}", data:{model_name: text.class.name.underscore, update_url:article_text_sort_path(@article) }}
            .text-box
              = text.text
              .operation-box.btn{id:"#{text.id}"}
                -# %li 上へ
                -# %li 下へ
                %li#text-delete{action:"/articles/#{@article.id}/texts/#{text.id}"} 削除

        -# 関連記事一覧
        -@relations.each do |relation|
          %div{class:"content-box", id:"#{relation.position.id}",index:"#{relation.position.position}", data:{model_name: relation.class.name.underscore, update_url:article_relation_sort_path(@article) }}
            =link_to edit_article_path(relation.relation) do
              .relation-box
                %h3
                  = Article.find(relation.relation).title
                %p
                  = Article.find(relation.relation).explanation
                .operation-box.btn{id:"#{relation.id}"}
                  -# %li 上へ
                  -# %li 下へ
                  %li#relation-delete{action:"/articles/#{@article.id}/relations/#{relation.id}"} 削除

      .article-create
        .article-create-tag
          %li 見出し
          %li 本文
          %li 関連記事
        .article-create-content
          %section.article-head
            = form_with url:article_heads_path(@article), class:'article-head-form', id:"form-head", remote:true do |f|
              .article-head-form-box
                = f.text_area :head, placeholder: "見出しを入力", id:"head-form",class:"#{@article.id}", required:true
              .article-head-form-btn
                = f.submit "保存する", { class: "btn btn-primary", id: 'head-submit'}
          %section.article-text
            = form_with url:article_texts_path(@article), class:'article-text-form', id:"form-text" do |f|
              .article-text-form-box
                = f.text_area :text, placeholder: "本文を入力", id:"text-form",required:true
              .article-text-form-btn
                = f.submit "保存する", { class: "btn btn-primary", id: 'text-submit'}
          %section.article-relation
            = form_with url:article_relations_path(@article), class:'article-relation-form', id:"form-relation" do |f|
              .article-relation-form-box
                = f.collection_select :relation, Article.all, :id, :title, {prompt: '---'}, id:"relation-form"
              .article-relation-form-btn
                = f.submit "保存する", { class: "btn btn-primary", id: 'relation-submit'}



  = link_to '記事一覧へ', articles_path, class:"top-link btn btn-outline-info"

app/views/articles/index.html.haml
.articles-top
  .articles-head
    %h1 記事一覧

  .articles
    = render @articles

app/views/articles/new.html.haml
%h1 New Article
= render 'form', article: @article
= link_to 'Back', articles_path

app/views/articles/show.html.haml
-# -# -binding.pry
-# .articles-top
-#   .articles-head
-#     %h1 記事編集（記事ID：
-#     %h1
-#       = @article.id
-#       %span )

-#   .article-edit
-#     .article-edit-box
-#       = form_with model:@article, method: :patch, class:'article-edit-box-form' do |f|
-#         %h3 ■タイトル
-#         .article-edit-box-title
-#           = f.text_area :title, value: @article.title, id:"title-form"
-#         %h3 ■説明文
-#         .article-edit-box-explanation
-#           = f.text_area :explanation, value: @article.explanation, id:"explanation-form"

-#     .article-edit-detail
-#       %h3 ■記事内容
-#       .article-edit-detail-container
-#         -# 見出し一覧
-#         -@article.heads.each do |head|
-#           .content-box{id:"head-#{head.id}"}
-#             .head-box
-#               = head.head
-#               .operation-box{id:"#{head.id}"}
-#                 %li 上へ
-#                 %li 下へ
-#                 %li#head-delete{action:"/articles/#{@article.id}/heads/#{head.id}"} 削除

-#         -# 本文一覧
-#         -@article.texts.each do |text|
-#           .content-box
-#             .text-box
-#               = text.text
-#               .operation-box{id:"#{text.id}"}
-#                 %li 上へ
-#                 %li 下へ
-#                 %li#text-delete{action:"/articles/#{@article.id}/texts/#{text.id}"} 削除

-#         -# 関連記事一覧
-#         -@article.relations.each do |relation|
-#           .content-box
-#             =link_to article_path(relation.relation) do
-#               .relation-box
-#                 %h3
-#                   = Article.find(relation.relation).title
-#                 %p
-#                   = Article.find(relation.relation).explanation
-#                 .operation-box{id:"#{relation.id}"}
-#                   %li 上へ
-#                   %li 下へ
-#                   %li#relation-delete{action:"/articles/#{@article.id}/relations/#{relation.id}"} 削除

-#       .article-create
-#         .article-create-tag
-#           %li 見出し
-#           %li 本文
-#           %li 関連記事
-#         .article-create-content
-#           %section.article-head
-#             = form_with url:article_heads_path(@article), class:'article-head-form', id:"form-head", remote:true do |f|
-#               .article-head-form-box
-#                 = f.text_area :head, placeholder: "見出しを入力", id:"head-form",required:true
-#               .article-head-form-btn
-#                 = f.submit "保存する", { class: "btn btn-primary", id: 'head-submit'}
-#           %section.article-text
-#             = form_with url:article_texts_path(@article), class:'article-text-form', id:"form-text" do |f|
-#               .article-text-form-box
-#                 = f.text_area :text, placeholder: "本文を入力", id:"text-form",required:true
-#               .article-text-form-btn
-#                 = f.submit "保存する", { class: "btn btn-primary", id: 'text-submit'}
-#           %section.article-relation
-#             = form_with url:article_relations_path(@article), class:'article-relation-form', id:"form-relation" do |f|
-#               .article-relation-form-box
-#                 = f.collection_select :relation, Article.all, :id, :title, {prompt: '---'}, id:"relation-form"
-#               .article-relation-form-btn
-#                 = f.submit "保存する", { class: "btn btn-primary", id: 'relation-submit'}



-#   = link_to '記事一覧へ', articles_path, class:"top-link btn btn-outline-info"