config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'

  resources :articles do
    put :head_sort
    put :text_sort
    put :relation_sort
    resources :relations
    resources :heads
    resources :texts
  end

end

app/models/text.rb
class Text < ApplicationRecord
  belongs_to :article
  has_one :position, dependent: :destroy
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  before_action :set_text, only: [:show, :edit, :update, :destroy]
  protect_from_forgery except:[:destroy]

  # GET /texts
  # GET /texts.json
  def index
    @texts = Text.all
  end

  # GET /texts/1
  # GET /texts/1.json
  def show
  end

  # GET /texts/new
  def new
    @text = Text.new
  end

  # GET /texts/1/edit
  def edit
  end

  # POST /texts
  # POST /texts.json
  def create
    @text = Text.new(text_params)
    @article = Article.find(params[:article_id])
    if @text.save
      # text作成時にそのidに紐付いたpositionも作成する
      @position = Position.new(text_id:@text.id, article_id:@article.id)
      @position.save
      render 'text.js.erb'
    else
      redirect_to article_path(params[:article_id])
    end
  end

  # PATCH/PUT /texts/1
  # PATCH/PUT /texts/1.json
  def update
    respond_to do |format|
      if @text.update(text_params)
        format.html { redirect_to @text, notice: 'Text was successfully updated.' }
        format.json { render :show, status: :ok, location: @text }
      else
        format.html { render :edit }
        format.json { render json: @text.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /texts/1
  # DELETE /texts/1.json
  def destroy
    if @text.destroy
      render "text-delete.js.erb"
    else
      redirect_to article_path(params[:article_id])
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_text
      @text = Text.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def text_params
      params.permit(:text).merge(article_id:params[:article_id])
    end
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/views/texts/_form.html.haml
= form_for @text do |f|
  - if @text.errors.any?
    #error_explanation
      %h2= "#{pluralize(@text.errors.count, "error")} prohibited this text from being saved:"
      %ul
        - @text.errors.full_messages.each do |message|
          %li= message

  .actions
    = f.submit 'Save'

app/views/texts/_text.html.haml
%div{class:"content-box",id:"#{text.position.id}",index:"#{text.position.position}", data:{model_name: text.class.name.underscore, update_url:article_text_sort_path(@article) }}
  .text-box
    = text.text
    .operation-box.btn{id:"#{text.id}"}
      -# %li 上へ
      -# %li 下へ
      %li#text-delete{action:"/articles/#{@article.id}/texts/#{text.id}"} 削除

app/views/texts/edit.html.haml
%h1 Editing text

= render 'form'

= link_to 'Show', @text
\|
= link_to 'Back', texts_path

app/views/texts/index.html.haml
%h1 Listing texts

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @texts.each do |text|
      %tr
        %td= link_to 'Show', text
        %td= link_to 'Edit', edit_text_path(text)
        %td= link_to 'Destroy', text, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Text', new_text_path

app/views/texts/new.html.haml
%h1 New text

= render 'form'

= link_to 'Back', texts_path

app/views/texts/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_text_path(@text)
\|
= link_to 'Back', texts_path

app/views/texts/text-delete.js.erb
<%# alert("本文を削除しました") %>

app/views/texts/text.js.erb
$(".article-edit-detail-container").append("<%= j(render partial:'texts/text', locals: { text: @text }) %>");
$('#text-form').val('');